name: bhc_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  appwrite: ^12.0.4
  board_datetime_picker: ^1.6.8
  collection: ^1.18.0
  currency_picker: ^2.0.21
  currency_textfield: ^4.11.0
  date_picker_plus: ^4.0.0
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.7.0
  hive_local_storage: ^1.1.1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.0.0
  phone_numbers_parser: ^8.3.0
  reactive_dropdown_search: ^3.0.2
  reactive_file_picker: ^3.0.0
  reactive_forms: ^17.0.1
  responsive_builder: ^0.7.0
  slugid: ^1.1.2
  sn_progress_dialog: ^1.1.4
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  vr_player: ^0.2.2
  avatar_better: ^0.0.7
  shimmer: ^3.0.0
  # shimmer_animation: ^2.2.1
  loading_indicator: ^3.1.1
  floating_bottom_bar: ^0.0.3
  flutter_credit_card: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/images/app_icon.png'

flutter_native_splash:
  background_image: 'assets/images/splash_screen.png'
  android_12:
    color: '#AE2425'
    icon_background_color: '#FFFFFF'


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800

